{
 "title": "Time series",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "src_port", "label": "Source Port", "query": "> 0" },
   { "name": "dst_port", "label": "Destination Port", "query": "< 1024" },
   { "name": "src_ip", "label": "Source IP Address", "query": "0.0.0.0/0" },
   { "name": "dst_ip", "label": "Destination IP Address", "query": "0.0.0.0/0" }
  ]
 },
 "panels": [
  {
   "title": "Throughput bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(last_switched,'1s'),\r\nsum(in_bytes) AS \"in_bytes\"\r\nFROM goflow_records\r\nWHERE\r\n$__timeFilter(last_switched)\r\nAND dst_port $dst_port AND src_port $src_port AND src_ip <<= '$src_ip' AND dst_ip <<= '$dst_ip'\r\nGROUP BY time ORDER BY time DESC;"
    }
   ]
  },
  {
   "title": "Packet rate",
   "type": "graph",
   "description": "Packet rate",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(last_switched,'1s'),\r\nsum(in_pkts) AS \"in_packets\"\r\nFROM goflow_records\r\nWHERE\r\n$__timeFilter(last_switched)\r\nAND dst_port $dst_port AND src_port $src_port AND src_ip <<= '$src_ip' AND dst_ip <<= '$dst_ip'\r\nGROUP BY time ORDER BY time DESC;"
    }
   ]
  },
  {
   "title": "Throughput by Port",
   "type": "graph",
   "description": "UDP and TCP port throughput for ports < 1024.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(last_switched,'1s'),\r\ndst_port::varchar(32) AS metric, sum(in_bytes) AS \"in_bytes\"\r\nFROM goflow_records\r\nWHERE\r\n$__timeFilter(last_switched)\r\nAND dst_port $dst_port AND src_port $src_port AND src_ip <<= '$src_ip' AND dst_ip <<= '$dst_ip'\r\nGROUP BY dst_port, time ORDER BY time DESC;"
    }
   ]
  }
 ]
}