{
 "title": "TopN",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "src_port", "label": "Source Port", "query": "> 0" },
   { "name": "dst_port", "label": "Destination Port", "query": "<  65536" },
   { "name": "src_ip", "label": "Source IP Address", "query": "0.0.0.0/0" },
   { "name": "dst_ip", "label": "Destination IP Address", "query": "0.0.0.0/0" },
   { "name": "top", "label": "Top", "query": "10, 1,2,5,10,15" }
  ]
 },
 "panels": [
  {
   "title": "TopN - By Destination Address",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  max(last_switched) as time,\n  dst_ip::varchar(32) AS metric,\n  sum(in_bytes) AS in_bytes\nFROM goflow_records\nWHERE\n  $__timeFilter(last_switched)\n  AND dst_port $dst_port AND src_port $src_port AND src_ip <<= '$src_ip' AND dst_ip <<= '$dst_ip'\nGROUP BY\n  metric\nORDER BY in_bytes desc\nLIMIT $top"
    }
   ]
  },
  {
   "title": "TopN - By Destination Port",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  max(last_switched) as time,\n  dst_port::varchar(32) AS metric,\n  sum(in_bytes) AS in_bytes\nFROM goflow_records\nWHERE\n  $__timeFilter(last_switched)\n  AND dst_port $dst_port AND src_port $src_port AND src_ip <<= '$src_ip' AND dst_ip <<= '$dst_ip'\nGROUP BY\n  metric\nORDER BY in_bytes desc\nLIMIT $top"
    }
   ]
  },
  {
   "title": "TopN - By Source Port",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  max(last_switched) as time,\n  src_port::varchar(32) AS metric,\n  sum(in_bytes) AS in_bytes\nFROM goflow_records\nWHERE\n  $__timeFilter(last_switched)\n  AND dst_port $dst_port AND src_port $src_port AND src_ip <<= '$src_ip' AND dst_ip <<= '$dst_ip'\nGROUP BY\n  metric\nORDER BY in_bytes desc\nLIMIT $top"
    }
   ]
  }
 ]
}